# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'iac-aad-deploy-dev'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login -u dami.olayokun@etalopo.com -p P@ssw0rd+1001
      az account set --subscription '031e997d-b908-4dd0-9dba-c440758aec29'

- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'iac-aad-deploy-dev'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmResourceGroupName: 'UoH-RG'
    backendAzureRmStorageAccountName: 'uohmlopssa'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true
