# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Destroy
    steps:

      - task: AzureKeyVault@2
        displayName: Access Keyvault for Credentials
        inputs:
          azureSubscription: 'iac-aad-deploy-dev'
          KeyVaultName: 'iac-keyv-dev'
          SecretsFilter: '*'
          RunAsPreJob: false

      - task: AzureCLI@2
        displayName: Login to Azure
        inputs:
          azureSubscription: 'iac-aad-deploy-dev'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az login -u dami.olayokun@etalopo.com -p $(secretName)
            az account set --subscription $(subscriptionId)

      - task: TerraformCLI@0
        displayName: Terraform Init & Remote Backend
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: 'iac-aad-deploy-dev'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmResourceGroupName: 'UoH-RG'
          backendAzureRmStorageAccountName: 'uohmlopssa'
          backendAzureRmKey: 'terraform.tfstate'
          allowTelemetryCollection: true

      - task: TerraformCLI@2
        displayName: Terraform Destroy
        inputs:
          command: 'destroy'
          allowTelemetryCollection: true